export const BASE_API = "http://localhost:8000/api/";
// export const BASE_API = process.env.BASE_API;
//export const BASE_API = "https://ped-tracker.herokuapp.com/api/";

export const FETCH_DEVICE_BEGIN = "FETCH_DEVICE_BEGIN";
export const FETCH_DEVICE_FAILURE = "FETCH_DEVICE_FAILURE";
export const FETCH_DEVICE_SUCCESS = "FETCH_DEVICE_SUCCESS";
export const FETCH_DEVICES_SUCCESS = "FETCH_DEVICES_SUCCESS";
export const FETCH_DEVICE_NEW = "FETCH_DEVICE_NEW";
export const FETCH_DEVICE_ADD = "FETCH_DEVICE_ADD";
export const FETCH_DEVICE_UPDATE = "FETCH_DEVICE_UPDATE";
export const FETCH_DEVICE_DELETE = "FETCH_DEVICE_DELETE";

export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_USER_NEW = "FETCH_USER_NEW";
export const FETCH_USER_ADD = "FETCH_USER_ADD";
export const FETCH_USER_UPDATE = "FETCH_USER_UPDATE";
export const FETCH_USER_DELETE = "FETCH_USER_DELETE";

export const FETCH_LOCATIONS_BEGIN = "FETCH_LOCATIONS_BEGIN";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAILURE = "FETCH_LOCATIONS_FAILURE";

export const SIGNIN = "SIGNIN";
export const SIGNOUT = "SIGNOUT";
export const SET_MSG = "SET_MSG";

export const FETCH_LOCATION_NEW = "FETCH_LOCATION_NEW";
export const FETCH_LOCATION_ADD = "FETCH_LOCATION_ADD";
export const FETCH_LOCATION_UPDATE = "FETCH_LOCATION_UPDATE";
export const FETCH_LOCATION_DELETE = "FETCH_LOCATION_DELETE";
export const FETCH_LOCATION_BEGIN = "FETCH_LOCATION_BEGIN";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAILURE = "FETCH_LOCATION_FAILURE";

export const FETCH_EVENTS_BEGIN = "FETCH_EVENTS_BEGIN";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";

export const FETCH_SIGNIN = "FETCH_SIGNIN";
export const FETCH_SIGNOUT = "FETCH_SIGNOUT";

export const USER_ONCHANGE = "USER_ONCHANGE";
export const DEVICE_ONCHANGE = "DEVICE_ONCHANGE";
export const FETCH_STATUS = "FETCH_STATUS";
