export const FETCH_DEVICE_BEGIN = "FETCH_DEVICE_BEGIN";
export const FETCH_DEVICE_SUCCESS = "FETCH_DEVICE_SUCCESS";
export const FETCH_DEVICE_FAILURE = "FETCH_DEVICE_FAILURE";
export const FETCH_DEVICE_ADD = "FETCH_DEVICE_ADD";
export const FETCH_DEVICE_UPDATE = "FETCH_DEVICE_UPDATE";
export const FETCH_DEVICE_DELETE = "FETCH_DEVICE_DELETE";
