export const BASE_API = "http://localhost:8000/api";

export const FETCH_DEVICE_BEGIN = "FETCH_DEVICE_BEGIN";
export const FETCH_DEVICE_FAILURE = "FETCH_DEVICE_FAILURE";
export const FETCH_DEVICE_SUCCESS = "FETCH_DEVICE_SUCCESS";
export const FETCH_DEVICES_SUCCESS = "FETCH_DEVICES_SUCCESS";
export const FETCH_DEVICE_ADD = "FETCH_DEVICE_ADD";
export const FETCH_DEVICE_UPDATE = "FETCH_DEVICE_UPDATE";
export const FETCH_DEVICE_DELETE = "FETCH_DEVICE_DELETE";
export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_USER_ADD = "FETCH_USER_ADD";
export const FETCH_USER_UPDATE = "FETCH_USER_UPDATE";
export const FETCH_USER_DELETE = "FETCH_USER_DELETE";
export const FETCH_LOCATIONS_BEGIN = "FETCH_LOCATIONS_BEGIN";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAILURE = "FETCH_LOCATIONS_FAILURE";
